title: 'Shama Barna'
description: ''

name: 'Shama Barna'
url: https://shamafarabi.github.io

theme: jekyll-theme-cayman


# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems:
  - jekyll-seo-tag
